services:

  configSrv:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: configSrv
    restart: always
    networks:
      app-network:
        ipv4_address: 172.19.0.10
    ports:
      - "27017:27017"
    volumes:
      - config-data:/data/db
    entrypoint: "mongod --configsvr --replSet config_server --bind_ip_all --port 27017"
#   command:
#     [
#       "--configsvr",  //запуск в режиме конфигурации
#       "--replSet",
#       "config_server",
#       "--bind_ip_all",
#       "--port",
#       "27017"
#     ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1:
    container_name: shard1
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    networks:
      app-network:
        ipv4_address: 172.19.0.11
    ports:
      - "27018:27017"
    volumes:
      - shard1-data:/data/db
    entrypoint: "mongod --shardsvr --replSet shard1 --bind_ip_all --port 27017"
#   command:
#     [
#       "--shardsvr", //запуск в режиме шардинга
#       "--replSet",
#       "shard1", //название реплики
#       "--bind_ip_all",
#       "--port",
#       "27018"
#     ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2:
    container_name: shard2
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    networks:
      app-network:
        ipv4_address: 172.19.0.12
    ports:
      - "27019:27017"
    volumes:
      - shard2-data:/data/db
    entrypoint: "mongod --shardsvr --replSet shard2 --bind_ip_all --port 27017"
#   command:
#     [
#       "--shardsvr", //запуск в режиме шардинга
#       "--replSet",
#       "shard2", //название реплики
#       "--bind_ip_all",
#       "--port",
#       "27019"
#     ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos_router:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27017"
    networks:
      app-network:
        ipv4_address: 172.19.0.13
    entrypoint: "mongos --configdb config_server/configSrv:27017 --bind_ip_all --port 27017"
#   command:
#     [
#       "mongos", 
#       "--configdb", 
#       "config_server/configSrv:27017",
#       "--bind_ip_all",
#       "--port",
#       "27020"
#     ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s  

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router"
      MONGODB_DATABASE_NAME: "somedb"

    networks:
      app-network:
        ipv4_address: 172.19.0.100

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24

volumes:
  config-data:
  shard1-data:
  shard2-data:
